# Copyright (c) 2019 Lightricks. All rights reserved.

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A template for serverless applications.

Resources:
  MyFirstLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: example-lambda-function
      Handler: entrypoint.handler
      Runtime: python3.7
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
      MemorySize: 512
      Timeout: 300
      CodeUri: ./code
      Events:
        ResizePicture:
          Type: S3
          Properties:
            Bucket: !Ref MySampleBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: upload/
                  - Name: suffix
                    Value: .jpg

  MySampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cloud-down-to-earth-bucket
